defmodule ExtractlyTest do
  use ExUnit.Case


  describe "do not edit warning" do 
   
    @default_message """
    <!--
    DO NOT EDIT THIS FILE
    It has been generated from a template by Extractly (https://github.com/RobertDober/extractly.git)
    and any changes you make in this file will most likely be lost
    -->
    """
    test "default behaviour" do
      result = Extractly.do_not_edit_warning

      assert result == @default_message
    end
  end

end
