defmodule Extractly.DoNotEdit do

  @moduledoc """
  Implements the storage of DO NOT EDIT warning messages for languages and various
  variations.
  """

  @warnings %{
    en: """
    DO NOT EDIT THIS FILE
    It has been generated from a template by Extractly (https://github.com/RobertDober/extractly.git)
    and any changes you make in this file will most likely be lost
    """,
    fr: """
    """
  }
  @doc """
  """
  def warning(opts) do
    """
    <!--
    #{@warnings[:en]}-->
    """
  end
  
end
